<?php

function favorites_menu()
{
    $items = array();
    $items['movies'] = array(
        'title' => "Favorite movies",
        'page callback' => 'movies_display',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['books'] = array(
        'title' => "Favorite books",
        'page callback' => 'books_display',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['songs'] = array(
        'title' => "Favorite songs",
        'page callback' => 'songs_display',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function movies_display()
{
    return '
        <ul>
            <li>Die Hard</li>
            <li>Spirited Away</li>
            <li>What Dreams May Come</li>
        </ul>
    ';
}

function books_display()
{
    return '
        <ul>
            <li>Stranger in a Strange Land</li>
            <li>The Martian</li>
            <li>The Gunslinger</li>
        </ul>
    ';
}

function songs_display()
{
    return '
        <ul>
            <li>Barbie Girl</li>
            <li>What a Wonderful World</li>
            <li>Kryptonite</li>
        </ul>
    ';
}
