<?php

function title_case_menu(){
  $items = array();
  $items['title_case'] = array (
    'title' => 'Title Case Thingy',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('title_case_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['title_case_success_page'] = array (
    'title' => 'Successssss',
    'page callback' => 'title_case_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

return $items;
}

function title_case_form() {
  $form['input_text'] = array(
    '#title' => 'Text to input',
    '#type' => 'textfield',
    '#description' => t('Please enter the text you would like to change to title case'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Go',
  );
return $form;
}

function title_case_form_submit($form, &$form_state) {
  $text_to_change = $form_state['values']['input_text'];
  $array_small_words = ['a', 'an', 'the', 'at', 'by', 'for', 'in', 'of', 'on', 'to', 'up', 'and', 'as', 'but', 'or', 'nor'];
  $input_words_as_array = explode(" ", $text_to_change);
  $output = array();
  $lc_output = array();
  foreach ($input_words_as_array as $word) {
      array_push($lc_output, strtolower($word));
  }
  foreach ($lc_output as $lc) {
      if(!in_array($lc, $array_small_words)) {
          $lc = ucfirst($lc);
      }
      array_push($output, $lc);
  }
  $changedtext_output = ucfirst(implode(" ", $output));
  $_SESSION['title_case_output'] = $changedtext_output;
  $form_state['redirect'] = 'title_case_success_page';
}

function title_case_success() {
  $output = '<p>'. $_SESSION['title_case_output'] . '</p>';
  return "Hooray! $output";
  }
