<?php

function comment_buddy_menu() {
    $items[''] = array();
    return $items;
}

function comment_buddy_comment_insert(){
    drupal_set_message("Thank you! Comment submitted!");
}

function comment_buddy_comment_update(){
    drupal_set_message("Your comment has been changed.");
}

function comment_buddy_comment_delete(){
    $_GET['destination'] = '';
    drupal_set_message("Comment deleted. Good work eating your words.");
}
