<?php

function hello_user_menu() {
    $items = array();
    $items['user_add_success'] = array(
        'title' => "New User Added",
        'page callback' => 'add_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function add_success() {
    return '<p>User successfully added.</p>';
}


function hello_user_user_insert(){
    $_GET['destination'] = 'user_add_success';
}
